import type { Metadata } from "next";
import AuthStatusComponent from '@/components/auth/AuthStatusComponent';

export const metadata: Metadata = {
  title: "Game",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthStatusComponent>
      {children}
    </AuthStatusComponent>
  );
}
